name: test-ios-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Bundler
        run: gem install bundler

      # - name: Install Fastlane Dependencies
      #   run: bundle install
      #   working-directory: fastlane

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build macOS App
        run: fastlane mac build

      - name: Run Tests
        run: fastlane mac test