name: test-ios-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v2
      # - run: fastlane tests

      - name: Run xcodebuild
        run: xcodebuild -showBuildSettings -scheme CleanerXcode -project ./CleanerXcode.xcodeproj 2>&1